#!/bin/sh

LSEP=
LSEPE=
RSEP=
RSEPE=

CLOCK=⌚
CALENDAR="📅 "
MUSIC=♫

WIDTH=${1}

SMALL=80
MEDIUM=140

if [ "$WIDTH" -gt "$MEDIUM" ]; then
	TITLE=$(radiotext title)
	ARTIST=$(radiotext artist)
	MPD="#[fg=colour252,bg=default,nobold,noitalics,nounderscore]$RSEP#[fg=colour16,bg=colour252,bold,noitalics,nounderscore] $MUSIC $ARTIST - $TITLE"
  date_colour='colour252'
fi

if [ "$WIDTH" -ge "$SMALL" ]; then
	ZOOM="$(tmux list-panes -F '#F' | grep -q Z)"
	if [ "$?" -eq "0" ]; then
		UNAME="#[fg=colour31,bg=colour236,nobold,noitalics,nounderscore]$RSEP#[fg=colour231,bg=colour31,bold,noitalics,nounderscore] Zoom "
	fi
fi

DATE="#[fg=colour236,bg=${date_colour:-default},nobold,noitalics,nounderscore]$RSEP#[fg=colour252,bg=colour236,nobold,noitalics,nounderscore] $CALENDAR $(date +'%a %d.%m.%Y')"
# TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$RSEPE#[fg=colour252,bg=colour236,bold,noitalics,nounderscore] $CLOCK $(date +'%H:%M')"
TIME="#[fg=colour241,bg=colour236,nobold,noitalics,nounderscore]$RSEPE#[fg=colour252,bg=colour236,bold,noitalics,nounderscore] $(date +'%H:%M')"

echo "$MPD $DATE $TIME $UNAME" | sed 's/ *$/ /g'
