alias rot13='php $DOTFILES/script/rot13.php'
alias code='cd ~/Documents/code'
alias gping='ping google.de'
alias week='expr `date +%W` + 1'
alias reload='source ~/.zshrc'
alias ...='cd ../..'
alias ....='cd ../../..'
